import { createContext, useContext, useState, useEffect, useCallback } from 'react'
import { fichasApi } from '../api.js'

const FichasContext = createContext(null)

// Categorías para fichas de Donación y Regalo
export const FICHA_CATEGORIES = [
  { id: 'transporte', label: '🚐 Transporte', emoji: '🚐' },
  { id: 'alimentacion', label: '🍕 Alimentación', emoji: '🍕' },
  { id: 'higiene', label: '🧴 Higiene', emoji: '🧴' },
  { id: 'bienestar', label: '💛 Bienestar', emoji: '💛' },
  { id: 'educacion', label: '📚 Educación', emoji: '📚' },
  { id: 'salud', label: '🏥 Salud', emoji: '🏥' },
  { id: 'limpieza', label: '🧹 Limpieza', emoji: '🧹' },
  { id: 'ropa', label: '👕 Ropa', emoji: '👕' },
  { id: 'otros', label: '📦 Otros', emoji: '📦' },
]

// Categorías específicas para fichas de Voluntariado
export const VOLUNTEER_CATEGORIES = [
  { id: 'mantenimiento', label: '🔧 Mantenimiento', emoji: '🔧' },
  { id: 'pintura', label: '🎨 Pintura', emoji: '🎨' },
  { id: 'limpieza', label: '🧹 Limpieza', emoji: '🧹' },
  { id: 'cocina', label: '🍳 Cocina', emoji: '🍳' },
  { id: 'recreacion', label: '🎉 Recreación', emoji: '🎉' },
  { id: 'educacion_vol', label: '📖 Educación', emoji: '📖' },
  { id: 'acompanamiento', label: '🤝 Acompañamiento', emoji: '🤝' },
]

// Categorías de insumos para inventario / especie
export const INSUMO_CATEGORIES = [
  { id: 'alimentos', label: '🍕 Alimentos', emoji: '🍕' },
  { id: 'higiene', label: '🧴 Higiene', emoji: '🧴' },
  { id: 'ropa', label: '👕 Ropa', emoji: '👕' },
  { id: 'medicamentos', label: '💊 Medicamentos', emoji: '💊' },
  { id: 'educacion', label: '📚 Material Escolar', emoji: '📚' },
  { id: 'limpieza', label: '🧹 Limpieza', emoji: '🧹' },
  { id: 'otros', label: '📦 Otros', emoji: '📦' },
]

// Tipos de ficha soportados
export const FICHA_TYPES = [
  { id: 'collaborative', label: '🤲 Voluntariado', description: 'Evento de voluntariado con cupos' },
  { id: 'gift', label: '🎁 Regalo', description: 'Monto fijo por unidad' },
  { id: 'donation', label: '💰 Donación', description: 'Donación libre hacia una meta' },
  { id: 'sponsorship', label: '🤝 Apadrinamiento', description: 'Oportunidad de apadrinamiento' },
]

export function FichasProvider({ children }) {
  const [fichas, setFichas] = useState([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(null)

  const fetchFichas = useCallback(async () => {
    try {
      const data = await fichasApi.getAll()
      setFichas(data)
      setError(null)
    } catch (err) {
      console.error('Error cargando fichas:', err)
      setError(err.message)
    } finally {
      setLoading(false)
    }
  }, [])

  useEffect(() => {
    fetchFichas()
  }, [fetchFichas])

  async function addFicha(fichaData) {
    try {
      const newFicha = await fichasApi.create(fichaData)
      setFichas(prev => [...prev, newFicha])
      return newFicha
    } catch (err) {
      console.error('Error creando ficha:', err)
      throw err
    }
  }

  async function deleteFicha(id) {
    try {
      await fichasApi.delete(id)
      setFichas(prev => prev.filter(f => f.id !== id))
    } catch (err) {
      console.error('Error eliminando ficha:', err)
      throw err
    }
  }

  async function updateFicha(id, data) {
    try {
      const updated = await fichasApi.update(id, data)
      setFichas(prev => prev.map(f => (f.id === id ? updated : f)))
      return updated
    } catch (err) {
      console.error('Error actualizando ficha:', err)
      throw err
    }
  }

  async function donateToFicha(id, donationData) {
    try {
      const updated = await fichasApi.donate(id, donationData)
      setFichas(prev => prev.map(f => (f.id === id ? updated : f)))
      return updated
    } catch (err) {
      console.error('Error donando:', err)
      throw err
    }
  }

  // Getters por tipo
  function getCollaborativeNeeds() {
    return fichas.filter(f => f.type === 'collaborative' && f.status !== 'cancelled')
  }

  function getGiftNeeds() {
    return fichas.filter(f => f.type === 'gift' && f.status !== 'cancelled')
  }

  function getDonationNeeds() {
    return fichas.filter(f => f.type === 'donation' && f.status !== 'cancelled')
  }

  function getSponsorshipNeeds() {
    return fichas.filter(f => f.type === 'sponsorship' && f.status !== 'cancelled')
  }

  function getAutoGeneratedFichas() {
    return fichas.filter(f => f.auto_generated === 1 && f.status === 'active')
  }

  function getAllNeeds() {
    return fichas.filter(f => f.status !== 'cancelled')
  }

  function getNeedById(id) {
    return fichas.find(f => f.id === id)
  }

  return (
    <FichasContext.Provider
      value={{
        fichas,
        loading,
        error,
        refreshFichas: fetchFichas,
        addFicha,
        deleteFicha,
        updateFicha,
        donateToFicha,
        getCollaborativeNeeds,
        getGiftNeeds,
        getDonationNeeds,
        getSponsorshipNeeds,
        getAutoGeneratedFichas,
        getAllNeeds,
        getNeedById,
      }}
    >
      {children}
    </FichasContext.Provider>
  )
}

export function useFichas() {
  const context = useContext(FichasContext)
  if (!context) {
    throw new Error('useFichas debe usarse dentro de un FichasProvider')
  }
  return context
}
